version: '3'
services:
  monitor:
    image: ${IMAGE}:${TAG:-latest}
    environment:
      INFURA_KEY: ${INFURA_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN:-}
      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK:-}
      TWITTER_TOKEN: ${TWITTER_TOKEN}
      TWITTER_TOKEN_SECRET: ${TWITTER_TOKEN_SECRET}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
    volumes:
      - type: bind
        source: "./config.js"
        target: "/token-monitor/dist/config.js"
    restart: always
